package org.octopus.common_business.town.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BaseProTown generated by MyEclipse - Hibernate Tools
 */
@Entity
@Table(name = "base_pro_town")
public class BaseProTown {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
     private Integer townId;
     private String provinceName;
     private String cityName;
     private String townName;
     private String provinceCode;
     private String degreePlace;
     private String regionalismName;
     private String regionalismCode;
     private String postalcode;
     private String areacode;
     private String isPoor;

    // Constructors

    public String getIsPoor() {
		return isPoor;
	}


	public void setIsPoor(String isPoor) {
		this.isPoor = isPoor;
	}


	/** default constructor */
    public BaseProTown() {
    }

    
    /** full constructor */
    public BaseProTown(String provinceName, String cityName, String townName, String provinceCode, String degreePlace, String regionalismName, String regionalismCode, String postalcode, String areacode) {
        this.provinceName = provinceName;
        this.cityName = cityName;
        this.townName = townName;
        this.provinceCode = provinceCode;
        this.degreePlace = degreePlace;
        this.regionalismName = regionalismName;
        this.regionalismCode = regionalismCode;
        this.postalcode = postalcode;
        this.areacode = areacode;
    }

   
    // Property accessors

    public Integer getTownId() {
        return this.townId;
    }
    
    public void setTownId(Integer townId) {
        this.townId = townId;
    }

    public String getProvinceName() {
        return this.provinceName;
    }
    
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getTownName() {
        return this.townName;
    }
    
    public void setTownName(String townName) {
        this.townName = townName;
    }

    public String getProvinceCode() {
        return this.provinceCode;
    }
    
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    public String getDegreePlace() {
        return this.degreePlace;
    }
    
    public void setDegreePlace(String degreePlace) {
        this.degreePlace = degreePlace;
    }

    public String getRegionalismName() {
        return this.regionalismName;
    }
    
    public void setRegionalismName(String regionalismName) {
        this.regionalismName = regionalismName;
    }

    public String getRegionalismCode() {
        return this.regionalismCode;
    }
    
    public void setRegionalismCode(String regionalismCode) {
        this.regionalismCode = regionalismCode;
    }

    public String getPostalcode() {
        return this.postalcode;
    }
    
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    public String getAreacode() {
        return this.areacode;
    }
    
    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }
    public String getDisplayCityCodeName(){
    	return this.cityName;
    }
    public String getDisplayCityCodeCode(){
    	return this.cityName;
    }
    public String getDisplayProvinceCodeName(){
    	return this.provinceName;
    }
    public String getDisplayProvinceCodeCode(){
    	return this.provinceCode;
    }

}