package cn.edu.sdu.uims.base;

import java.awt.Component;
import java.beans.PropertyChangeListener;
import java.io.Serializable;
import java.util.HashMap;

import cn.edu.sdu.common.form.UFormI;
import cn.edu.sdu.common.reportdog.UColor;
import cn.edu.sdu.common.reportdog.UFont;
import cn.edu.sdu.common.reportdog.UTemplate;
import cn.edu.sdu.uims.component.menu.UMenu;
import cn.edu.sdu.uims.component.menu.UPopupMenu;
import cn.edu.sdu.uims.def.UElementTemplate;
import cn.edu.sdu.uims.def.UEventAttribute;
import cn.edu.sdu.uims.filter.FilterI;
import cn.edu.sdu.uims.handler.UHandlerI;
import cn.edu.sdu.uims.trans.URect;

public interface UComponentI extends  Serializable, PropertyChangeListener {

	void init();
	void setShellBounds(int x, int y, int w, int h);
	URect getBoundRect();
	int getWidth();
	int getHeight();
	void setTemplate(UTemplate template);
	UTemplate getTemplate();
	void setHorizontalAlignment(int arg0);
	void setVerticalAlignment(int arg0);
	void setText(String arg0);
	void setColor(UColor c);
	void setBackground(UColor c);
	void setBorder(UBorder border);
	void setBorder(int width, UColor color);
	void setFont(UFont agr0);
	boolean requestFirstFoucus();
	void setData(Object obj);
	Object getData();
	boolean hasEmptyFileds();
	public void setFilter(FilterI filter);
	public FilterI getFilter();
	public void setFilter1(FilterI filter);
	public boolean isEditable();
	public void setEditable(boolean b);
	public boolean isVisible();
	public void setVisible(boolean b);
	public boolean isEnabled();
	public void setEnabled(boolean b);
	public Component getAWTComponent();
	public void setArrangeType( int type);
	public void addEvents(UEventAttribute events[]);
	public void setAddedDatas(Object[] obj );
	public void updateAddedDatas();
	public UPanelI getUParent();
	public void setUParent(UPanelI parent);
	public void  setHandler(UHandlerI handler);
	public void setComponentName(String name);
	public String getComponentName();
	public void setPopupMenu(UMenu menu);
	public void initContents();
	public void setInitComponentData(Object data);
	public String getText();
	public void resetShellBounds(int x, int y, int w, int h);
	public void onClose();
	public void repaintComponent();
	public void setParameters(HashMap paras);
	public HashMap getParameters();
	public void setElementTemplate(UElementTemplate elementTemplate);
	public UElementTemplate getElementTemplate();
	public void setdisplayText(String text);
	public String getdisplayText();
	public String getActionComandString();
	public void setActionComandString(String str);
	public void processDispControlAfterInited();
	Object  getSelectedValue();
	int[] getSelectedIndices();
	public UPopupMenu getUPopupMenu();
	void sendDataToForm(UFormI form);
	Object[] getAddedInnerTextFiledValues();
	void  clearAddedInnerTextFiled();
	void setScreenOwner(UComponentI screenOwner);
	UComponentI getSubComponent(String name);
	void setUserData(Object obj);
	void setEnablePopupMenu(boolean enable);
	void setLabel(String label);
	Object getCurrentSelectObject();
	String getSelectedText();
	void insertText(String text);
}
