package cn.edu.sdu.uims.constant;

public interface UConstants {
	int SA = 1;
	int SB = 1;

	/** 字库名称 */
	String WordName = "WordBase.mdb";
	/** 字库扄1�7在服务器的地坄1�7 */
	String WordSrcPath = "D:\\pinyin\\WordBase.mdb";

	String MODE_WORK_PATH = "uims\\configure\\";

	String defultDesignElementClassName = "cn.edu.sdu.uims.view.UVText";
	int SPLIT_WIDTH = 5;
	int SCROLL_WIDTH = 12;

	int UIMS_TYPE_FORM = 0;
	int UIMS_TYPE_VIEW = 1;
	int UIMS_TYPE_PAGE = 2;
	int UIMS_TYPE_DOC = 3;
	int UIMS_TYPE_SHEET = 4;
	int UIMS_TYPE_PRINT = 5;
	int UIMS_TYPE_DIALOG = 6;

	char MARKCHAR = '@';
	char RETURNCHAR = '\n';

	String KEY_STRING_FONT = "font";
	String KEY_STRING_STROKE = "stroke";
	String KEY_STRING_HANDLER = "handler";
	String KEY_STRING_COLOR = "color";
	String KEY_STRING_POINTCURSOR = "pointCursor";
	String KEY_STRING_UISTYLE = "uistyle";
	String KEY_STRING_PAPER = "paper";
	String KEY_STRING_PROMPT = "prompt";
	String KEY_STRING_FILTER = "filter";
	String KEY_STRING_DICTIONARYMAPPING = "dictionaryMapping";
	String KEY_STRING_PARAGRAPH = "paragraph";
	String KEY_STRING_PAGENUMBER = "pagenumber";
	String KEY_STRING_BORDER = "border";
	String KEY_STRING_DIALOG = "dialog";
	String KEY_STRING_FORMPANEL = "formPanel";
	String KEY_STRING_PRINTPANEL = "printPanel";
	String KEY_STRING_PRINTDATATABLE = "printDataTable";
	String KEY_STRING_MENUMAP = "menuMap";
	String CS_MENU_TYPE = "CS_MENU_TYPE";
	String CS_TREE_TYPE = "CS_TREE_TYPE";

	String KEY_STRING_CURSOR = "cursor";
	String KEY_STRING_EVENTOR = "eventor";
	String KEY_STRING_STATUSDIAGRAM = "statusdiagram";
	String KEY_STRING_TASK = "task";
	String KEY_STRING_USER_TASK = "userTask";

	String KEY_STRING_CLIENTFRAME = "clientFrame";
	String KEY_STRING_CLIENTDIALOG = "clientDialog";
	String KEY_STRING_ROOMLAYOUT = "roomLayout";
	String KEY_STRING_PHOTOLAYOUT = "photoLayout";
	String KEY_STRING_DATATEST_INFO = "dataTestInfo";
	String KEY_STRING_DATATEST_PROCESS = "dataTestProcess";

	String TYPEDEF_MAP_KEY = "mapKey";
	String TYPEDEF_LAYOUT_MODE = "layoutMode";
	String TYPEDEF_COMPONENT_TYPE = "componentType";
	String TYPEDEF_PARAGRAPH_TYPE = "paragraphType";
	String TYPEDEF_PAGE_NUMBER_LAYOUT_TYPE = "pageNumberLayoutType";
	String TYPEDEF_PAGE_NUMBER_TYPE = "pageNumberType";
	String TYPEDEF_BORDER_LAYOUT_TYPE = "borderLayoutType";
	String TYPEDEF_ALIGNMENT_TYPE = "alignmentType";
	String TYPEDEF_FONT_STYLE_TYPE = "fontStyleType";
	String TYPEDEF_ARRANGE_TYPE = "arrangeType";
	String TYPEDEF_CHART_TYPE = "chartType";
	String TYPEDEF_EVENT_TYPE = "eventType";
	String TYPEDEF_ROW_ARRANGE_TYPE = "rowArrangeType";
	String TYPEDEF_DATE_STYLE = "dateStyle";

	int DATA_MODE_NUMBER = 1;
	int DATA_MODE_CHINESE = 2;

	String MAPKEY_DICTIONARYMAPPING = "1000";
	String MAPKEY_FILTER = "1001";
	String MAPKEY_HANDLER = "1002";
	String MAPKEY_ROOMLAYOUT = "1003";

	String MAPKEY_FONT = "1011";
	String MAPKEY_COLOR = "1012";
	String MAPKEY_PAPER = "1013";
	String MAPKEY_PARAGRAPH = "1014";
	String MAPKEY_PAGENUMBER = "1015";
	String MAPKEY_BORDER = "1016";
	/** 刘洋添加：增加了画笔属性 */
	String MAPKEY_STROKE = "1017";
	String MAPKEY_POINTCURSOR = "1018";
	String MAPKEY_UISTYLE = "1019";
	String MAPKEY_PROMPT = "1020";

	String MAPKEY_FIX_TABLE_FORM = "1021";
	String MAPKEY_FIX_TABLE_VIEW = "1022";
	String MAPKEY_FIX_TABLE_PAGE = "1023";

	String MAPKEY_DATA_TABLE_FORM = "1031";
	String MAPKEY_DATA_TABLE_VIEW = "1032";
	String MAPKEY_DATA_TABLE_PAGE = "1033";
	String MAPKEY_DATA_TABLE_DOC = "1034";
	String MAPKEY_DATA_TABLE_SHEET = "1035";

	String MAPKEY_RANDOM_TABLE_FORM = "1041";
	String MAPKEY_RANDOM_TABLE_VIEW = "1042";
	String MAPKEY_RANDOM_TABLE_PAGE = "1043";
	String MAPKEY_RANDOM_TABLE_DOC = "1044";
	String MAPKEY_RANDOM_TABLE_SHEET = "1045";
	String MAPKEY_DATA_IO = "1046";

	String MAPKEY_CURSOR = "1051";
	String MAPKEY_EVENTOR = "1052";
	String MAPKEY_STATUSDIAGRAM = "1053";
	String MAPKEY_TASK = "1054";
	String MAPKEY_USER_TASK = "1055";

	String MAPKEY_CHART_VIEW = "1061";

	String MAPKEY_MENU = "1081";
	String MAPKEY_TOOLBAR = "1082";
	String MAPKEY_GRAPHTOOLBAR = "10821";
	String MAPKEY_STATUSBAR = "1083";
	String MAPKEY_PROGREEBAR = "1084";
	String MAPKEY_SHORTCUTKEY = "1085";
	String MAPKEY_GRAPHBUTTONBAR = "1086";

	String MAPKEY_PANEL_FORM = "1091";
	String MAPKEY_PANEL_VIEW = "1092";
	String MAPKEY_PANEL_PAGE = "1033";
	String MAPKEY_PANEL_DOC = "1094";
	String MAPKEY_PANEL_SHEET = "1095";
	String MAPKEY_PANEL_PRINT = "1096";
	String MAPKEY_PANEL_OLDCSPANEL = "1097";

	String MAPKEY_NOPANEL_ACTION = "1110";

	String MAPKKEY_CLIENTFRAME = "1112";

	String MAPKKEY_CLIENTDIALOG = "1114";

	String MAPKKEY_VISUAL = "1113";

	String MAPKEY_DIALOG = "1098";
	String MAPKEY_WORKBENCH = "1099";
	String MAPKEY_MENUMAP = "1100";

	String LAYOUTMODE_LOCATE = "locate";
	String LAYOUTMODE_SHIFT = "shift";
	String LAYOUTMODE_PAGE_LABEL = "pageLabel";
	String LAYOUTMODE_PAGE_LIST = "pageList";
	String LAYOUTMODE_PAGE_TREE = "pageTree";
	String LAYOUTMODE_PAGE_ICON = "pageIcon";
	String LAYOUTMODE_PAGE = "page";
	String LAYOUTMODE_TABLE = "table";
	String LAYOUTMODE_HDIV = "hdiv";
	String LAYOUTMODE_VDIV = "vdiv";
	String LAYOUTMODE_VHDIV = "vhdiv";
	String LAYOUTMODE_HVDIV = "hvdiv";
	String LAYOUTMODE_BORDER = "border";
	String LAYOUTMODE_FLOW = "flow";
	String LAYOUTMODE_HIDEABLE = "hideable";
	String LAYOUTMODE_VHDIV_NS = "vhdivns";
	String LAYOUTMODE_HVDIV_NS = "hvdivns";
	String LAYOUTMODE_ONE = "one";

	int COMPONENT_LOCATE = 201;
	int COMPONENT_SHIFT = 202;
	int COMPONENT_DEFINE = 203;

	int COMPONENT_LABLE = 211;
	int COMPONENT_LABLE_TITLE = 2111;
	int COMPONENT_LABLE_MULTI_LINE = 2112;
	int COMPONENT_TEXTFIELD = 212;
	int COMPONENT_NUMBERFIELD = 2121;
	int COMPONENT_NUMBERFIELDWITHADDMINUS = 2122;
	int COMPONENT_PASSWORDFIELD = 2123;
	int COMPONENT_TEXTFIELDCHECK = 2124;
	int COMPONENT_TEXTFIELDPINYIN = 2125;
	int COMPONENT_TEXTFIELDUINT = 2126;
	int COMPONENT_BUTTON = 213;
	int COMPONENT_RADIOBUTTON = 2131;
	int COMPONENT_RADIOGROUP = 2132;
	int COMPONENT_CHECKBOX = 214;
	int COMPONENT_CHECKBOXGROUP = 2141;
	int COMPONENT_GEDIT = 215;
	int COMPONENT_COMBOBOX = 216;
	int COMPONENT_COMBOBOXTYPE = 2161;
	int COMPONENT_COMBOBOXDATA = 2162;
	int COMPONENT_LIST = 217;
	int COMPONENT_LISTSELECT = 2171;
	int COMPONENT_TREE = 218;
	int COMPONENT_TEXTAREA = 219;
	int COMPONENT_SEPARATOR = 220;
	int COMPONENT_PROGRESSBAR = 2201;

	int COMPONENT_LINE = 221;
	int COMPONENT_BOX = 222;
	int COMPONENT_TEXT = 223;
	int COMPONENT_PARAGRAPH = 224;
	int COMPONENT_IMAGE = 225;
	int COMPONENT_BARCODE = 226;
	int COMPONENT_DATE = 227;

	int COMPONENT_TABLE_FIX_FORM = 231;
	int COMPONENT_TABLE_FIX_VIEW = 232;
	int COMPONENT_TABLE_FIX_PAGE = 233;

	int COMPONENT_TABLE_DATA_FORM = 241;
	int COMPONENT_TABLE_DATA_VIEW = 242;
	int COMPONENT_TABLE_DATA_PAGE = 243;
	int COMPONENT_TABLE_DATA_DOC = 244;
	int COMPONENT_TABLE_DATA_SHEET = 245;

	int COMPONENT_TABLE_RANDOM_FORM = 251;
	int COMPONENT_TABLE_RANDOM_VIEW = 252;
	int COMPONENT_TABLE_RANDOM_PAGE = 253;
	int COMPONENT_TABLE_RANDOM_DOC = 254;

	int COMPONENT_COMPLEX_IMPORTXLS = 1211;

	int COMPONENT_MENU_MENU = 281;// 配置项名-菜单
	int COMPONENT_MENU_ITEM = 282;// 配置项名-菜单项
	int COMPONENT_RADIO_MENU_ITEM = 283;// 配置项名-radio菜单

	int COMPONENT_GRAPH_VIEW = 271;
	int COMPONENT_GRAPH_VIEW_REGION = 272;
	int COMPONENT_GRAPH_TOOLBAR = 273;
	int COMPONENT_GRAPH_BUTTONBAR = 274;
	int COMPONENT_GRAPH_CUBE = 275;

	int PARAGRAPH_TEXT = 501;
	int PARAGRAPH_HEADING0 = 502;
	int PARAGRAPH_HEADING1 = 503;
	int PARAGRAPH_HEADING2 = 504;
	int PARAGRAPH_HEADING3 = 505;
	int PARAGRAPH_HEADING4 = 506;
	int PARAGRAPH_HEADING5 = 507;

	int PAGENUMBER_LAYOUT_NULL = 511;
	int PAGENUMBER_LAYOUT_CENTER = 512;
	int PAGENUMBER_LAYOUT_RIGHTBOTTOM = 513;
	int PAGENUMBER_LAYOUT_OUT = 514;

	int PAGENUMBER_CODE_1 = 521;

	int BORDER_LAYOUT_NULL = 901;
	int BORDER_LAYOUT_ALL = 902;
	int BORDER_LAYOUT_BOTTOM = 903;
	int BORDER_LAYOUT_TOP = 904;
	int BORDER_LAYOUT_LEFT = 905;
	int BORDER_LAYOUT_RIGHT = 906;

	int ALIGNMENT_CENTER = 0;
	int ALIGNMENT_TOP = 1;
	int ALIGNMENT_LEFT = 2;
	int ALIGNMENT_BOTTOM = 3;
	int ALIGNMENT_RIGHT = 4;
	int ALIGNMENT_TIP = 10;
	int ALIGNMENT_LEADING = 11;
	int ALIGNMENT_TRAILING = 12;
	int ALIGNMENT_NULL = -1;

	int ROW_ARRANGE_CLOSE = 1;
	int ROW_ARRANGE_LOOSE = 2;

	int TEXTARRANGE_HORIZONTAL = 0;
	int TEXTARRANGE_VERTICAL = 1;
	int TEXTARRANGE_GRID = 2;
	int TEXTARRANGE_FLOW = 3;

	int CHART_CELL = 0;
	int CHART_HISTOGRAM = 1;
	int CHART_PIE = 2;
	int CHART_CURVE = 3;

	int COMPONENT_PAGEPANEL = 293; // bs component
	int COMPONENT_RESET = 2001;// BS 重置标签
	int COMPONENT_SUBMIT = 2002;// BS 提交标签
	int COMPONENT_HIDDENTEXTFIELD = 2003;// BS隐藏表单域
	int COMPONENT_FILE = 2004;// BS文件控件
	int COMPONENT_PASSWORD = 2005;// 密码控件
	int COMPONENT_HREF = 2006;// 超链接
	int COMPONENT_SPAN = 2007;
	int COMPONENT_PLABEL = 2008;
	String XMLPAGEMODULE_KEY = "cn.edu.sdu.uims.def.UPageConfigModule";
	final String XMLVALIDATIONMODULE = "XMLVALIDATIONMODULE";

	double chartOffset = -0.08; // 用JFreeChart绘制图的x轴偏移量

	int DRAG_LINE = 1; // 拖放直线
	int DRAG_RECTANGE = 2; // 拖放矩形
	int DRAG_POLYGONLINE = 3; // 拖放多边形
	int DRAG_OVAL = 4; // 拖放椭圆形

	int GRID_BAG_FILL_NONE = 0;
	int GRID_BAG_FILL_BOTH = 1;
	int GRID_BAG_FILL_HORIZONTAL = 2;
	int GRID_BAG_FILL_VERTICAL = 3;

	int GRID_BAG_ANCHOR_CENTER = 10;
	int GRID_BAG_ANCHOR_NORTH = 11;
	int GRID_BAG_ANCHOR_NORTHEAST = 12;
	int GRID_BAG_ANCHOR_EAST = 13;
	int GRID_BAG_ANCHOR_SOUTHEAST = 14;
	int GRID_BAG_ANCHOR_SOUTH = 15;
	int GRID_BAG_ANCHOR_SOUTHWEST = 16;
	int GRID_BAG_ANCHOR_WEST = 17;
	int GRID_BAG_ANCHOR_NORTHWEST = 18;

	String MODEL_KEY_GRAPH = "9001";
	String MODEL_TYPE_GRAPH = "01";
	String MODEL_TYPE_GRAPH_PRINT = "01";
	String MODEL_TYPE_GRAPH_ROOMPLANE = "02";
	String MODEL_TYPE_GRAPH_CLASSROM = "03";
	
	Integer SCHEDULE_DAY_NUM = 7;
	Integer SCHEDULE_SECTION_NUM= 12;

	
	
}
