package cn.edu.sdu.uims.graph.form;

import javax.sql.rowset.serial.SerialBlob;



/**
 * 人员照片信息
 * InfoPhoto generated by MyEclipse - Hibernate Tools
 */

public class InfoPhotoForm  extends AddedAttributeForm implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String photoType;//照片类型
     private String remark;//备注
     private SerialBlob photo;
     private String fileName;
     private Integer personId;
     private String perName;
     private String perTypeCode;
     private String perNum;
     private String perAddress;
     private String perTelephone;
     private String exameeType;

    // Constructors
   

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/** default constructor */
    public InfoPhotoForm() {
    }

	/** minimal constructor */

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


    public String getPhotoType() {
        return this.photoType;
    }
    
    public void setPhotoType(String photoType) {
        this.photoType = photoType;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public SerialBlob getPhoto() {
		return photo;
	}

	public void setPhoto(SerialBlob photo) {
		this.photo = photo;
	}

	public Integer getPersonId() {
		return personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public String getPerName() {
		return perName;
	}

	public void setPerName(String perName) {
		this.perName = perName;
	}

	public String getPerNum() {
		return perNum;
	}

	public void setPerNum(String perNum) {
		this.perNum = perNum;
	}

	public String getPerAddress() {
		return perAddress;
	}

	public void setPerAddress(String perAddress) {
		this.perAddress = perAddress;
	}

	public String getPerTelephone() {
		return perTelephone;
	}

	public void setPerTelephone(String perTelephone) {
		this.perTelephone = perTelephone;
	}

	public String getPerTypeCode() {
		return perTypeCode;
	}

	public void setPerTypeCode(String perTypeCode) {
		this.perTypeCode = perTypeCode;
	}

	public String getExameeType() {
		return exameeType;
	}

	public void setExameeType(String exameeType) {
		this.exameeType = exameeType;
	}
	
	
	
}