/* Generated By:JavaCC: Do not edit this line. CCJSqlParserConstants.java */
/*
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2014 JSQLParser
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */

package net.sf.jsqlparser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCJSqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_AS = 5;
  /** RegularExpression Id. */
  int K_BY = 6;
  /** RegularExpression Id. */
  int K_DO = 7;
  /** RegularExpression Id. */
  int K_IS = 8;
  /** RegularExpression Id. */
  int K_IN = 9;
  /** RegularExpression Id. */
  int K_OR = 10;
  /** RegularExpression Id. */
  int K_ON = 11;
  /** RegularExpression Id. */
  int K_ALL = 12;
  /** RegularExpression Id. */
  int K_AND = 13;
  /** RegularExpression Id. */
  int K_ANY = 14;
  /** RegularExpression Id. */
  int K_KEY = 15;
  /** RegularExpression Id. */
  int K_NOT = 16;
  /** RegularExpression Id. */
  int K_SET = 17;
  /** RegularExpression Id. */
  int K_ASC = 18;
  /** RegularExpression Id. */
  int K_TOP = 19;
  /** RegularExpression Id. */
  int K_PERCENT = 20;
  /** RegularExpression Id. */
  int K_END = 21;
  /** RegularExpression Id. */
  int K_DESC = 22;
  /** RegularExpression Id. */
  int K_INTO = 23;
  /** RegularExpression Id. */
  int K_NULL = 24;
  /** RegularExpression Id. */
  int K_LIKE = 25;
  /** RegularExpression Id. */
  int K_DROP = 26;
  /** RegularExpression Id. */
  int K_JOIN = 27;
  /** RegularExpression Id. */
  int K_LEFT = 28;
  /** RegularExpression Id. */
  int K_CROSS = 29;
  /** RegularExpression Id. */
  int K_FROM = 30;
  /** RegularExpression Id. */
  int K_OPEN = 31;
  /** RegularExpression Id. */
  int K_CASE = 32;
  /** RegularExpression Id. */
  int K_WHEN = 33;
  /** RegularExpression Id. */
  int K_THEN = 34;
  /** RegularExpression Id. */
  int K_ELSE = 35;
  /** RegularExpression Id. */
  int K_SOME = 36;
  /** RegularExpression Id. */
  int K_FULL = 37;
  /** RegularExpression Id. */
  int K_WITH = 38;
  /** RegularExpression Id. */
  int K_TABLE = 39;
  /** RegularExpression Id. */
  int K_VIEW = 40;
  /** RegularExpression Id. */
  int K_WHERE = 41;
  /** RegularExpression Id. */
  int K_FOR = 42;
  /** RegularExpression Id. */
  int K_PIVOT = 43;
  /** RegularExpression Id. */
  int K_XML = 44;
  /** RegularExpression Id. */
  int K_USING = 45;
  /** RegularExpression Id. */
  int K_UNION = 46;
  /** RegularExpression Id. */
  int K_GROUP = 47;
  /** RegularExpression Id. */
  int K_BEGIN = 48;
  /** RegularExpression Id. */
  int K_INDEX = 49;
  /** RegularExpression Id. */
  int K_INNER = 50;
  /** RegularExpression Id. */
  int K_LIMIT = 51;
  /** RegularExpression Id. */
  int K_OUTER = 52;
  /** RegularExpression Id. */
  int K_ORDER = 53;
  /** RegularExpression Id. */
  int K_RIGHT = 54;
  /** RegularExpression Id. */
  int K_VALUE = 55;
  /** RegularExpression Id. */
  int K_DELETE = 56;
  /** RegularExpression Id. */
  int K_CREATE = 57;
  /** RegularExpression Id. */
  int K_SELECT = 58;
  /** RegularExpression Id. */
  int K_OFFSET = 59;
  /** RegularExpression Id. */
  int K_EXISTS = 60;
  /** RegularExpression Id. */
  int K_HAVING = 61;
  /** RegularExpression Id. */
  int K_INSERT = 62;
  /** RegularExpression Id. */
  int K_UPDATE = 63;
  /** RegularExpression Id. */
  int K_VALUES = 64;
  /** RegularExpression Id. */
  int K_ESCAPE = 65;
  /** RegularExpression Id. */
  int K_PRIMARY = 66;
  /** RegularExpression Id. */
  int K_NATURAL = 67;
  /** RegularExpression Id. */
  int K_REPLACE = 68;
  /** RegularExpression Id. */
  int K_BETWEEN = 69;
  /** RegularExpression Id. */
  int K_TRUNCATE = 70;
  /** RegularExpression Id. */
  int K_DISTINCT = 71;
  /** RegularExpression Id. */
  int K_INTERSECT = 72;
  /** RegularExpression Id. */
  int K_CAST = 73;
  /** RegularExpression Id. */
  int K_EXCEPT = 74;
  /** RegularExpression Id. */
  int K_MINUS = 75;
  /** RegularExpression Id. */
  int K_OVER = 76;
  /** RegularExpression Id. */
  int K_PARTITION = 77;
  /** RegularExpression Id. */
  int K_EXTRACT = 78;
  /** RegularExpression Id. */
  int K_LATERAL = 79;
  /** RegularExpression Id. */
  int K_MATERIALIZED = 80;
  /** RegularExpression Id. */
  int K_INTERVAL = 81;
  /** RegularExpression Id. */
  int K_FOREIGN = 82;
  /** RegularExpression Id. */
  int K_CONSTRAINT = 83;
  /** RegularExpression Id. */
  int K_REFERENCES = 84;
  /** RegularExpression Id. */
  int K_CHARACTER = 85;
  /** RegularExpression Id. */
  int K_VARYING = 86;
  /** RegularExpression Id. */
  int K_START = 87;
  /** RegularExpression Id. */
  int K_CONNECT = 88;
  /** RegularExpression Id. */
  int K_PRIOR = 89;
  /** RegularExpression Id. */
  int K_NOCYCLE = 90;
  /** RegularExpression Id. */
  int K_SIBLINGS = 91;
  /** RegularExpression Id. */
  int K_ALTER = 92;
  /** RegularExpression Id. */
  int K_ADD = 93;
  /** RegularExpression Id. */
  int K_COLUMN = 94;
  /** RegularExpression Id. */
  int K_NULLS = 95;
  /** RegularExpression Id. */
  int K_FIRST = 96;
  /** RegularExpression Id. */
  int K_LAST = 97;
  /** RegularExpression Id. */
  int K_ROWS = 98;
  /** RegularExpression Id. */
  int K_RANGE = 99;
  /** RegularExpression Id. */
  int K_UNBOUNDED = 100;
  /** RegularExpression Id. */
  int K_PRECEDING = 101;
  /** RegularExpression Id. */
  int K_FOLLOWING = 102;
  /** RegularExpression Id. */
  int K_CURRENT = 103;
  /** RegularExpression Id. */
  int K_ROW = 104;
  /** RegularExpression Id. */
  int K_RETURNING = 105;
  /** RegularExpression Id. */
  int K_BINARY = 106;
  /** RegularExpression Id. */
  int K_REGEXP = 107;
  /** RegularExpression Id. */
  int K_UNLOGGED = 108;
  /** RegularExpression Id. */
  int K_EXEC = 109;
  /** RegularExpression Id. */
  int K_EXECUTE = 110;
  /** RegularExpression Id. */
  int K_FETCH = 111;
  /** RegularExpression Id. */
  int K_NEXT = 112;
  /** RegularExpression Id. */
  int K_ONLY = 113;
  /** RegularExpression Id. */
  int K_COMMIT = 114;
  /** RegularExpression Id. */
  int K_UNIQUE = 115;
  /** RegularExpression Id. */
  int K_WITHIN = 116;
  /** RegularExpression Id. */
  int K_IF = 117;
  /** RegularExpression Id. */
  int S_DOUBLE = 118;
  /** RegularExpression Id. */
  int S_LONG = 119;
  /** RegularExpression Id. */
  int DIGIT = 120;
  /** RegularExpression Id. */
  int LINE_COMMENT = 121;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 122;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 123;
  /** RegularExpression Id. */
  int LETTER = 124;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 125;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 126;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 127;
  /** RegularExpression Id. */
  int ADDITIONAL_LETTERS = 128;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"AS\"",
    "\"BY\"",
    "\"DO\"",
    "\"IS\"",
    "\"IN\"",
    "\"OR\"",
    "\"ON\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"KEY\"",
    "\"NOT\"",
    "\"SET\"",
    "\"ASC\"",
    "\"TOP\"",
    "\"PERCENT\"",
    "\"END\"",
    "\"DESC\"",
    "\"INTO\"",
    "\"NULL\"",
    "\"LIKE\"",
    "\"DROP\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"CROSS\"",
    "\"FROM\"",
    "\"OPEN\"",
    "\"CASE\"",
    "\"WHEN\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"SOME\"",
    "\"FULL\"",
    "\"WITH\"",
    "\"TABLE\"",
    "\"VIEW\"",
    "\"WHERE\"",
    "\"FOR\"",
    "\"PIVOT\"",
    "\"XML\"",
    "\"USING\"",
    "\"UNION\"",
    "\"GROUP\"",
    "\"BEGIN\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"LIMIT\"",
    "\"OUTER\"",
    "\"ORDER\"",
    "\"RIGHT\"",
    "\"VALUE\"",
    "\"DELETE\"",
    "\"CREATE\"",
    "\"SELECT\"",
    "\"OFFSET\"",
    "\"EXISTS\"",
    "\"HAVING\"",
    "\"INSERT\"",
    "\"UPDATE\"",
    "\"VALUES\"",
    "\"ESCAPE\"",
    "\"PRIMARY\"",
    "\"NATURAL\"",
    "\"REPLACE\"",
    "\"BETWEEN\"",
    "\"TRUNCATE\"",
    "\"DISTINCT\"",
    "\"INTERSECT\"",
    "\"CAST\"",
    "\"EXCEPT\"",
    "\"MINUS\"",
    "\"OVER\"",
    "\"PARTITION\"",
    "\"EXTRACT\"",
    "\"LATERAL\"",
    "\"MATERIALIZED\"",
    "\"INTERVAL\"",
    "\"FOREIGN\"",
    "\"CONSTRAINT\"",
    "\"REFERENCES\"",
    "\"CHARACTER\"",
    "\"VARYING\"",
    "\"START\"",
    "\"CONNECT\"",
    "\"PRIOR\"",
    "\"NOCYCLE\"",
    "\"SIBLINGS\"",
    "\"ALTER\"",
    "\"ADD\"",
    "\"COLUMN\"",
    "\"NULLS\"",
    "\"FIRST\"",
    "\"LAST\"",
    "\"ROWS\"",
    "\"RANGE\"",
    "\"UNBOUNDED\"",
    "\"PRECEDING\"",
    "\"FOLLOWING\"",
    "\"CURRENT\"",
    "\"ROW\"",
    "\"RETURNING\"",
    "\"BINARY\"",
    "\"REGEXP\"",
    "\"UNLOGGED\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"FETCH\"",
    "\"NEXT\"",
    "\"ONLY\"",
    "\"COMMIT\"",
    "\"UNIQUE\"",
    "\"WITHIN\"",
    "\"IF\"",
    "<S_DOUBLE>",
    "<S_LONG>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<ADDITIONAL_LETTERS>",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\".\"",
    "\"?\"",
    "\"(+)\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"!=\"",
    "\"@@\"",
    "\"~\"",
    "\"~*\"",
    "\"!~\"",
    "\"!~*\"",
    "\"||\"",
    "\"|\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"{d\"",
    "\"}\"",
    "\"{t\"",
    "\"{ts\"",
    "\"::\"",
    "\":\"",
    "\"@\"",
    "\"->\"",
    "\"{fn\"",
  };

}
